version: '3.6'
services:
  postgres:
    image: postgres:12.2
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: .
    ports:
    - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
volumes:
  db_data:


